## Creating Arrays

NumPy is used to work with arrays. 
The array object in NumPy is called ndarray.

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
## We can use a tuple to create a NumPy array.

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


## Dimension in Array

A Dimension in arrays is one level of array depth(nested arrays).

In [9]:
## 0 Dimension Array
arr = np.array(42)
print(arr)

np.ndim(arr)

42


0

In [11]:
## 1 Dimension Array
arr = np.array([1,2,3,4,5])
print(arr)

np.ndim(arr)

[1 2 3 4 5]


1

In [ ]:
## 2 Dimension array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

np.ndim(arr)

[[1 2 3]
 [4 5 6]]


2

In [14]:
## 3 Dimension Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

np.ndim(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [15]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
## N dimentional array
arr = np.array([1,2,3,4], ndmin= 5)
print(arr)

np.ndim(arr)

[[[[[1 2 3 4]]]]]


5

#### *Indexing is same as other data types.