In [1]:
import numpy as np

## Q1. Create a 1D array with values ranging from 0 to 9.

In [5]:
a1 = np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


## Q2. Convert a 1D array to a 2D array with 2 rows.

In [7]:
arr = np.arange(10).reshape(2,-1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Q3. Multiply a 5x3 matrix by a 3x2 matrix.

In [18]:
# randint(start, stop, total_numbers)
np.random.seed(45)
a1 = np.random.randint(1,50,15).reshape(5,3)
a2 = np.random.randint(1,50,6).reshape(3,2)

result = np.dot(a1, a2)
print(result)

[[1003  979]
 [1625 2429]
 [ 881 1949]
 [ 563  616]
 [1649 1802]]


In [21]:
mat1 = np.random.random((5, 3))
mat2 = np.random.random((3, 2))
result = np.dot(mat1, mat2)
print(result)

[[1.3494932  0.59657157]
 [0.91181345 0.29399058]
 [0.6163066  0.22441044]
 [1.08991393 0.38941233]
 [0.79566983 0.44000284]]


## Q4. Extract all odd numbers from an array of 1-10.

In [20]:
arr = np.arange(11)
odd_num = arr[arr % 2 != 0]
print(odd_num)

[1 3 5 7 9]


## Q5. Replace all odd numbers in an array of 1-10 with -1.

In [22]:
arr = np.arange(11)
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


## Q6. Convert a 1D array to a boolean array where all positive values become True.

In [2]:
arr = np.array([1,2,-3,-4,5,6,-7,-8])
boolean_arr =  arr > 0
print(boolean_arr)

[ True  True False False  True  True False False]


## Q7. Replace all even numbers in a 1D array with their negative.

In [4]:
arr = np.arange(1,11)
arr[arr % 2 == 0] *= -1
print(arr)

[  1  -2   3  -4   5  -6   7  -8   9 -10]


## Q8. Create a random 3x3 matrix and normalize it.

In [11]:
# np.random.random(size = None)
np.random.seed(65)
matrix = np.random.random((3,3))
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)

[[-0.55281576 -1.33323145 -0.26739396]
 [-0.74454287 -0.19966026 -0.78494873]
 [ 1.45058483  1.75149827  0.68050992]]


## Q9. Calculate the sum of the diagonal elements of a 3x3 matrix.

In [13]:
matrix = np.random.random((3, 3))
diagonal_sum = np.trace(matrix)
print(diagonal_sum)

1.4263225779347715


## Q10. Find the indices of non-zero elements from [1,2,0,0,4,0].

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

## np.nonzero(data) ---> It gives the indices of non-zero elements in an array.

(array([0, 1, 4]),)


## Q11. Reverse a 1D array (first element becomes the last).

In [2]:
arr = np.array([12,13,14,21,22,23,34,35,36], ndmin= 1)
reverse = np.flip(arr)
print(reverse)

[36 35 34 23 22 21 14 13 12]


## Q12. Create a 3x3 identity matrix.

In [3]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Q13. Reshape a 1D array to a 2D array with 5 rows and 2 columns.

In [6]:
arr = np.arange(60,90, 3)
new_arr = arr.reshape(5,2)
print(new_arr)

[[60 63]
 [66 69]
 [72 75]
 [78 81]
 [84 87]]


## Q14. Stack two arrays vertically.

In [8]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
stacked = np.vstack((a1,a2))
print(stacked)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Q15. Get the common items between two arrays.

In [9]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
common_items = np.intersect1d(arr1, arr2)
print(common_items)

[3 4 5]
