In [ ]:
import numpy as np

In [ ]:
## Question 1. What is the difference between List and Numpy.?

## List ---> List is a data type in Python in which a collection of data can be stored and can have Heterogeneous type of data.
## NumPy ---> NumPy is a Library of Python in which a homogeneous type of data is stored.

In [ ]:
## Question 2. Create a User defined array.?
a = []
size = int(input("Enter the size of array: "))
dim = int(input("Enter Dimension: "))

for i in range(size):
    val = int(input("Enter your values: "))
    a.append(val)

arr = np.array(a, ndmin= dim)
print(type(arr))
print(arr)

In [ ]:
## Question 3. Create a random array in range 100 to 200 and total values will be 64. and you have to reshape
## all the factors.

arr = np.random.randint(100,200,64)
print(arr.reshape(32,2))
print("\n")
print(arr.reshape(2,32))
print("\n")
print(arr.reshape(16,4))
print("\n")
print(arr.reshape(4,16))
print("\n")
print(arr.reshape(8,8))

In [46]:
## Question 4. Create a array of 5*5 in which all the values will be 7?
arr = np.full((5, 5), 7)
print(arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [47]:
## Question 5. Explain view vs copy with examples.?
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
b = a[1:4]
b[:] = 0
print(b)
print(a)

c = a[4:7].copy()
c[:] = 0
print(c)
print(a)

[1 2 3 4 5 6 7 8 9]
[0 0 0]
[1 0 0 0 5 6 7 8 9]
[0 0 0]
[1 0 0 0 5 6 7 8 9]


In [48]:
## Question 6 . Difference between linspace() and Unique() with examples.?
arr1 = np.linspace(1,10,5)
print(arr1)   ## By using linspace it will return 5 elements under range 1 to 10 with same gaping.

arr2 = np.array([10,11,11,12,12,12,12,13,13,13,13,13,14,14,14,14,15,16,16])
print(np.unique(arr2, return_index= True, return_counts= True))   ## ---> By using unique function it will return unique elements from the array.

[ 1.    3.25  5.5   7.75 10.  ]
(array([10, 11, 12, 13, 14, 15, 16]), array([ 0,  1,  3,  7, 12, 16, 17]), array([1, 2, 4, 5, 4, 1, 2]))


In [49]:
## Question 7. What is horizontal stacking and vertical stacking
# Create an array and connect it with vstack and hstack.
a = np.array((1,2,3))
b = np.array((4,5,6))
c = np.array((7,8,9))

print(np.vstack((a,b,c)))
print("\n")
print(np.hstack((a,b,c)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3 4 5 6 7 8 9]


In [50]:
## Question 8. Create an array in range 11-26. Now reshape it 4*4 and then calculate sum, row-wise sum and column wise sum.?
arr = np.arange(11,27).reshape(4,4)
print(arr)
print("\n")
print(np.sum(arr, axis = 0))
print("\n")
print(np.sum(arr, axis = 1))

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]


[68 72 76 80]


[50 66 82 98]
