## NumPY

In [1]:
# NumPY is an open-source library that is used for handle scientific calculations.

# Difference between List and NumPY---
# (1). List is Heterogeneous data type and Numpy is Homogeneous data type.
# (2). List takes more memory as compared to Numpy
# (3). List takes more execution time as compared to Numpy.

In [2]:
## Installation
# pip install numpy ---> for VS Code
# !pip install numpy ---> for jupyter notebook
# uv add -r requirements.txt ---> for uv in VS Code.

In [ ]:
# !pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [8]:
a = [1,45,78,90]
print(type(a))

b = np.array(a)
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
## User-Defined Array
a = []
size = int(input("Enter Size: "))

for i in range(size):
    val = int(input("Enter Item: "))
    a.append(val)
# print(a)
b = np.array(a)
print(b)

print(type(b))

In [10]:
a = [[1,2,3], [4,5,6], [7,8,9]]
# print(a)
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Matrix ---. rows, columns

#row_1 = [1,2,3]
#row_2 = [4,5,6]
#row_3 = [7,8,9]

# col_1 = [1,4,7]
# col_2 = [2,5,8]
# col_3 = [3,6,9]

#Total Elements = row * column = 3 * 3 = 9

In [12]:
print("Total Rows and Columns: ", b.shape)
print("Total Elements: ", b.size)

Total Rows and Columns:  (3, 3)
Total Elements:  9


In [14]:
c = [[1,2,3,5], [4,5,6,8], [7,8,9,10]]
d = np.array(c)
print(d)

[[ 1  2  3  5]
 [ 4  5  6  8]
 [ 7  8  9 10]]


In [15]:
print("Total Rows and Columns: ", d.shape)
print("Total Elements: ", d.size)

Total Rows and Columns:  (3, 4)
Total Elements:  12


In [24]:
## How to check dimension of an Matrix?
e = np.array([1,3,4])
# print(e)
print(e.ndim)

f = np.array([[1,2,3],[4,5,6]])
print(f)
print(f.ndim)

g = np.array([[[1,2,3],[4,5,6]]])
print(g.ndim)

1
[[1 2 3]
 [4 5 6]]
2
3


In [25]:
## Why we use NumPy

# Images ---> Pixels(0-255) ---> Normalize(0-1) ---> Matrix ---> Operations
# DL ---> Artificial Neurons ---> Weight ---> randomly creation ---> Numpy
# Datasets ---> Dummy Entry ---> random module ---> attach pandas

In [ ]:
# Pre-Defined Function in Numpy
# (1). zeros() ---> It will create an array in which all the values will be zero in either 1-D or multi-dimentional

h = np.zeros(3)
print(h)

i = np.zeros((3,4))
print(i)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# (2). ones()---> It will create an array in which all the values will be 1 in either 1-D or multi-dimentional
j = np.ones(4)
print(j)
print("\n")
k = np.ones((4,5))
print(k)

[1. 1. 1. 1.]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# (3). eye() ---> It will create an array in which diagonal positional elements will be 1 and rest all are 0.
# Syntax : eye(rows, columns)
a = np.eye(3)                 ## Symmetric Matrix
print(a)          
print("\n")
b = np.eye(3,4)               ## Asymmetric Matrix  ---> rows != columns
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# (4). diag() ---> It will create an array in which we can set our custom values at diagonal position.
a = np.diag([43,34,67,90])
print(a)

[[43  0  0  0]
 [ 0 34  0  0]
 [ 0  0 67  0]
 [ 0  0  0 90]]




In [7]:
# (5). Random Module
# (a). randint() ---> It will create an array randomly in a given range.
# syntax : np.random.randint(min_range, max_range, total_numbers)

a = np.random.randint(1,10,3)
print(a)

[7 5 3]


In [8]:
# (b). rand() ---> It will generate random numbers from 0 - 1.
# syntax : np.random.rand(total_random_number)

a = np.random.rand(4)
print(a)

[0.67049424 0.11170113 0.08791668 0.68455181]


In [ ]:
## Suppose we have
# dataset(emp_data)(emp-id, salary, domain) ---> randomly column add (working_hours)

In [14]:
# (c). seed() ---> It will fix or lock our generated data.
# syntax : np.random.seed(45)
# a = np.random.randint(1,10,2)

np.random.seed(34)
a = np.random.randint(1,10,3)
print(a)

## Now our value is locked with the seed value '45'.

[2 7 6]


In [ ]:
# (d). view and copy
a = np.array([10,20,30,40,50,60,70,80,90])
print(a)

b = a[1:4]
b[:] = 0
print(b)
print(a)

[10 20 30 40 50 60 70 80 90]
[0 0 0]
[10  0  0  0 50 60 70 80 90]


In [18]:
## Copy
a = np.array([10,20,30,40,50,60,70,80,90])
b = a[1:4].copy()
b[:] = 0
print(b)
print(a)

[0 0 0]
[10 20 30 40 50 60 70 80 90]


In [2]:
## Reshaping the Array
# Condition ---> total_rows * total_columns = total_elements
a = np.random.randint(1,50,12)
print(a)

[35 11 30 19 26 12  6  2 32  8 40 35]


In [4]:
## Factors--->
# 1*12    12*1
# 2*6     6*2
# 3*4     4*3
# Syntax : reshape(rows,columns)

a.reshape(2,6)
print(a.reshape(3,4))
print("\n")
print(a.reshape(4,3))

# print(a.reshape(6,3)) ----> ValueError

[[35 11 30 19]
 [26 12  6  2]
 [32  8 40 35]]


[[35 11 30]
 [19 26 12]
 [ 6  2 32]
 [ 8 40 35]]


In [24]:
# We know
# y = mx + c
# m = Matrix ---> weights
# x = values ---> Matrix

#Multiplication rule ---> matrix(column)  *  (row)matrix

In [26]:
a = np.random.randint(1,50,12)
print(a.shape)

(12,)


In [ ]:
## Principle of -1
print(a.reshape(-1,3))      
print("\n")
print(a.reshape(2, -1))

[[46 21  9]
 [43 14 37]
 [ 3 38 35]
 [43 12 35]]


[[46 21  9 43 14 37]
 [ 3 38 35 43 12 35]]


In [ ]:
## Operation on Array
## arange() ---> Syntax : np.arange(start, stop, step)

a = np.arange(1,5,2)
print(a)

[1 3]


In [ ]:
a = np.arange(1,5)
print(a)

print(a*2)

[1 2 3 4]
[2 4 6 8]
[5 6 7 8]


In [38]:
a = np.arange(1,5).reshape(2,2)
print(a)
print("\n")
b = np.arange(5,9).reshape(2,2)
print(b)

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


In [40]:
print(a+b,"\n")
print(a-b,"\n")
print(a*b,"\n")

## Matrix Multiplication
a.dot(b)

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]] 



array([[19, 22],
       [43, 50]])

In [ ]:
a = np.arange(1,15)

print(a>10,"\n")

b = a > 10      ## We use logical operators on operations
print(a[b])

[False False False False False False False False False False  True  True
  True  True] 

[11 12 13 14]


In [46]:
a = np.arange(1,4)
print(a**2)
print(a**3)

[1 4 9]
[ 1  8 27]


In [12]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
np.sum(a)   ## Sum of all Elements

np.int64(45)

In [13]:
np.sum(a, axis = 1)     ## axis = 1 means row wise operation

array([ 6, 15, 24])

In [14]:
np.sum(a, axis = 0)    ## axis = 0 means column wise opeartion

array([12, 15, 18])

In [2]:
# Unique ---> It will create an array in which it will remove all the duplicate values and return 3 arrays
## arr ----> Unique elements of array
## return_index = True ---> Indexing of unique elements
## return_counts = True ---> Frequency of each unique elements.

In [3]:
a = np.array([1,2,3,1,1,1,1,4,5,4,4,4,4,4,4,6,7])
print(a)

[1 2 3 1 1 1 1 4 5 4 4 4 4 4 4 6 7]


In [ ]:
b = np.unique(a, return_index = True, return_counts = True)
print(b)

(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  2,  7,  8, 15, 16]), array([5, 1, 1, 7, 1, 1, 1]))


In [3]:
# linspace() ---> It will return an array in which elements will be same gap in a given range.
# Syntax : np.linspace(min_num, max_num, total_numbers)

a = np.linspace(1,2,5)
print(a)

[1.   1.25 1.5  1.75 2.  ]


In [11]:
## Horizontal and Vertical Stacking
# Horizontal Stacking ---> It will add 2 or more arrays horizontally.

a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

print(np.hstack((a,b,c)))
print("\n")
print(np.vstack((a,b,c)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
